cmd: git add -A;git commit -a -m "auto";git push origin master
targets:
  publish:
      cmd: "npm run build;cp ./dist.yaml /home/zoernert/Development/molecular/public-corrently-api/public; cd /home/zoernert/Development/molecular/public-corrently-api/; git commit -a 7-m 'Documentation updated';git push origin;"
