docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli generate  -i https://corrently.io/dist.yaml -g go -o /local/out/go
docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli generate  -i https://corrently.io/dist.yaml -g php -o /local/out/php
docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli generate  -i https://corrently.io/dist.yaml -g typescript-jquery -o /local/out/typescript-jquery
docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli generate  -i https://corrently.io/dist.yaml -g python -o /local/out/python
docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli generate  -i https://corrently.io/dist.yaml -g java -o /local/out/java
docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli generate  -i https://corrently.io/dist.yaml -g nodejs -o /local/out/nodejs
docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli generate  -i https://corrently.io/dist.yaml -g html -o /local/out/html
docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli generate  -i https://corrently.io/dist.yaml -g javascript -o /local/out/javascript
docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli generate  -i https://corrently.io/dist.yaml -g nodejs-express-server -o /local/out/nodejs-express-server
docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli generate  -i https://corrently.io/dist.yaml -g dynamic-html -o /local/out/dynamic-html
